//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteleSmsMessagingKit.NrdbService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Nrdb Lookup ServiceSoap", Namespace="intelesms.services", ConfigurationName="NrdbService.NrdbLookupServiceSoap")]
    public interface NrdbLookupServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="intelesms.services/Query", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        InteleSmsMessagingKit.NrdbService.NrdbStatus Query(InteleSmsMessagingKit.NrdbService.LoginClass login, long mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="intelesms.services/Query", ReplyAction="*")]
        System.Threading.Tasks.Task<InteleSmsMessagingKit.NrdbService.NrdbStatus> QueryAsync(InteleSmsMessagingKit.NrdbService.LoginClass login, long mobile);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="intelesms.services")]
    public partial class LoginClass : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int customerIdField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("CustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="intelesms.services")]
    public partial class NrdbStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ErrorCodeEnum errorCodeField;
        
        private string errorCodeDescriptionField;
        
        private long msisdnField;
        
        private int mncField;
        
        private int mccField;
        
        private int spidField;
        
        private System.DateTime queryDateField;
        
        private bool hasChangedField;
        
        private int queriesLeftField;
        
        private int queryTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ErrorCodeEnum ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorCodeDescription {
            get {
                return this.errorCodeDescriptionField;
            }
            set {
                this.errorCodeDescriptionField = value;
                this.RaisePropertyChanged("ErrorCodeDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long Msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
                this.RaisePropertyChanged("Msisdn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Mnc {
            get {
                return this.mncField;
            }
            set {
                this.mncField = value;
                this.RaisePropertyChanged("Mnc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Mcc {
            get {
                return this.mccField;
            }
            set {
                this.mccField = value;
                this.RaisePropertyChanged("Mcc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Spid {
            get {
                return this.spidField;
            }
            set {
                this.spidField = value;
                this.RaisePropertyChanged("Spid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime QueryDate {
            get {
                return this.queryDateField;
            }
            set {
                this.queryDateField = value;
                this.RaisePropertyChanged("QueryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool HasChanged {
            get {
                return this.hasChangedField;
            }
            set {
                this.hasChangedField = value;
                this.RaisePropertyChanged("HasChanged");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int QueriesLeft {
            get {
                return this.queriesLeftField;
            }
            set {
                this.queriesLeftField = value;
                this.RaisePropertyChanged("QueriesLeft");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int QueryTime {
            get {
                return this.queryTimeField;
            }
            set {
                this.queryTimeField = value;
                this.RaisePropertyChanged("QueryTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="intelesms.services")]
    public enum ErrorCodeEnum {
        
        /// <remarks/>
        ClientSystemError,
        
        /// <remarks/>
        ClientInvalidLogin,
        
        /// <remarks/>
        ClientMaxQueryReached,
        
        /// <remarks/>
        ClientInvalidMsisdn,
        
        /// <remarks/>
        ClientInetFailure,
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        RemoteInvalidMsisdn,
        
        /// <remarks/>
        RemoteNonExistingNumber,
        
        /// <remarks/>
        RemoteSystemError,
        
        /// <remarks/>
        RemoteMaxQueryReached,
        
        /// <remarks/>
        RemoteInvalidLogin,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NrdbLookupServiceSoapChannel : InteleSmsMessagingKit.NrdbService.NrdbLookupServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NrdbLookupServiceSoapClient : System.ServiceModel.ClientBase<InteleSmsMessagingKit.NrdbService.NrdbLookupServiceSoap>, InteleSmsMessagingKit.NrdbService.NrdbLookupServiceSoap {
        
        public NrdbLookupServiceSoapClient() {
        }
        
        public NrdbLookupServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NrdbLookupServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NrdbLookupServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NrdbLookupServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public InteleSmsMessagingKit.NrdbService.NrdbStatus Query(InteleSmsMessagingKit.NrdbService.LoginClass login, long mobile) {
            return base.Channel.Query(login, mobile);
        }
        
        public System.Threading.Tasks.Task<InteleSmsMessagingKit.NrdbService.NrdbStatus> QueryAsync(InteleSmsMessagingKit.NrdbService.LoginClass login, long mobile) {
            return base.Channel.QueryAsync(login, mobile);
        }
    }
}
