//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteleSmsMessagingKit.SmsSoapApi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="SMS gatewaySoap", Namespace="intelesms.services", ConfigurationName="SmsSoapApi.SMSgatewaySoap")]
    public interface SMSgatewaySoap {
        
        // CODEGEN: Generating message contract since message SendSMSRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="intelesms.services/SendSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        InteleSmsMessagingKit.SmsSoapApi.SendSMSResponse SendSMS(InteleSmsMessagingKit.SmsSoapApi.SendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="intelesms.services/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<InteleSmsMessagingKit.SmsSoapApi.SendSMSResponse> SendSMSAsync(InteleSmsMessagingKit.SmsSoapApi.SendSMSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="intelesms.services")]
    public partial class Authorizer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int customerIDField;
        
        private string passwordField;
        
        private string customDataField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("CustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string CustomData {
            get {
                return this.customDataField;
            }
            set {
                this.customDataField = value;
                this.RaisePropertyChanged("CustomData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="intelesms.services")]
    public partial class ResponseObj : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int statusCodeField;
        
        private string statusDescriptionField;
        
        private string extraInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
                this.RaisePropertyChanged("StatusDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string ExtraInfo {
            get {
                return this.extraInfoField;
            }
            set {
                this.extraInfoField = value;
                this.RaisePropertyChanged("ExtraInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="intelesms.services")]
    public partial class SMSMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gatewayField;
        
        private string originatorAddressField;
        
        private string destinationAddressField;
        
        private int priceField;
        
        private string messageTypeField;
        
        private string validationPeriodeField;
        
        private string validationPeriodField;
        
        private string messageIDField;
        
        private string userDataHeaderField;
        
        private string userDataField;
        
        private string categoryField;
        
        private string customDataField;
        
        private string deliveryReportUrlField;
        
        private string serviceCodeField;
        
        private string serviceDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Gateway {
            get {
                return this.gatewayField;
            }
            set {
                this.gatewayField = value;
                this.RaisePropertyChanged("Gateway");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string OriginatorAddress {
            get {
                return this.originatorAddressField;
            }
            set {
                this.originatorAddressField = value;
                this.RaisePropertyChanged("OriginatorAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DestinationAddress {
            get {
                return this.destinationAddressField;
            }
            set {
                this.destinationAddressField = value;
                this.RaisePropertyChanged("DestinationAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string MessageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
                this.RaisePropertyChanged("MessageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string ValidationPeriode {
            get {
                return this.validationPeriodeField;
            }
            set {
                this.validationPeriodeField = value;
                this.RaisePropertyChanged("ValidationPeriode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string ValidationPeriod {
            get {
                return this.validationPeriodField;
            }
            set {
                this.validationPeriodField = value;
                this.RaisePropertyChanged("ValidationPeriod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("MessageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string UserDataHeader {
            get {
                return this.userDataHeaderField;
            }
            set {
                this.userDataHeaderField = value;
                this.RaisePropertyChanged("UserDataHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string UserData {
            get {
                return this.userDataField;
            }
            set {
                this.userDataField = value;
                this.RaisePropertyChanged("UserData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string CustomData {
            get {
                return this.customDataField;
            }
            set {
                this.customDataField = value;
                this.RaisePropertyChanged("CustomData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DeliveryReportUrl {
            get {
                return this.deliveryReportUrlField;
            }
            set {
                this.deliveryReportUrlField = value;
                this.RaisePropertyChanged("DeliveryReportUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ServiceCode {
            get {
                return this.serviceCodeField;
            }
            set {
                this.serviceCodeField = value;
                this.RaisePropertyChanged("ServiceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ServiceDescription {
            get {
                return this.serviceDescriptionField;
            }
            set {
                this.serviceDescriptionField = value;
                this.RaisePropertyChanged("ServiceDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMS", WrapperNamespace="intelesms.services", IsWrapped=true)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="intelesms.services")]
        public InteleSmsMessagingKit.SmsSoapApi.Authorizer Authorizer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="intelesms.services", Order=0)]
        public InteleSmsMessagingKit.SmsSoapApi.SMSMessage smsObj;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(InteleSmsMessagingKit.SmsSoapApi.Authorizer Authorizer, InteleSmsMessagingKit.SmsSoapApi.SMSMessage smsObj) {
            this.Authorizer = Authorizer;
            this.smsObj = smsObj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMSResponse", WrapperNamespace="intelesms.services", IsWrapped=true)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="intelesms.services", Order=0)]
        public InteleSmsMessagingKit.SmsSoapApi.ResponseObj SendSMSResult;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(InteleSmsMessagingKit.SmsSoapApi.ResponseObj SendSMSResult) {
            this.SendSMSResult = SendSMSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SMSgatewaySoapChannel : InteleSmsMessagingKit.SmsSoapApi.SMSgatewaySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSgatewaySoapClient : System.ServiceModel.ClientBase<InteleSmsMessagingKit.SmsSoapApi.SMSgatewaySoap>, InteleSmsMessagingKit.SmsSoapApi.SMSgatewaySoap {
        
        public SMSgatewaySoapClient() {
        }
        
        public SMSgatewaySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSgatewaySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSgatewaySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSgatewaySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InteleSmsMessagingKit.SmsSoapApi.SendSMSResponse InteleSmsMessagingKit.SmsSoapApi.SMSgatewaySoap.SendSMS(InteleSmsMessagingKit.SmsSoapApi.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public InteleSmsMessagingKit.SmsSoapApi.ResponseObj SendSMS(InteleSmsMessagingKit.SmsSoapApi.Authorizer Authorizer, InteleSmsMessagingKit.SmsSoapApi.SMSMessage smsObj) {
            InteleSmsMessagingKit.SmsSoapApi.SendSMSRequest inValue = new InteleSmsMessagingKit.SmsSoapApi.SendSMSRequest();
            inValue.Authorizer = Authorizer;
            inValue.smsObj = smsObj;
            InteleSmsMessagingKit.SmsSoapApi.SendSMSResponse retVal = ((InteleSmsMessagingKit.SmsSoapApi.SMSgatewaySoap)(this)).SendSMS(inValue);
            return retVal.SendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InteleSmsMessagingKit.SmsSoapApi.SendSMSResponse> InteleSmsMessagingKit.SmsSoapApi.SMSgatewaySoap.SendSMSAsync(InteleSmsMessagingKit.SmsSoapApi.SendSMSRequest request) {
            return base.Channel.SendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<InteleSmsMessagingKit.SmsSoapApi.SendSMSResponse> SendSMSAsync(InteleSmsMessagingKit.SmsSoapApi.Authorizer Authorizer, InteleSmsMessagingKit.SmsSoapApi.SMSMessage smsObj) {
            InteleSmsMessagingKit.SmsSoapApi.SendSMSRequest inValue = new InteleSmsMessagingKit.SmsSoapApi.SendSMSRequest();
            inValue.Authorizer = Authorizer;
            inValue.smsObj = smsObj;
            return ((InteleSmsMessagingKit.SmsSoapApi.SMSgatewaySoap)(this)).SendSMSAsync(inValue);
        }
    }
}
